### ISSUE TITLE
Question and/or suggestion 1.14.4

### ISSUE THREAD

**Issue by DatrixTHLK** [JayJay1989/NoJumpingAllowed#1]
I like this mod. Since I have this mod installed I have changed my jump key so I don't accidentally press it while playing minecraft. The question I should ask is why does the game kill you for jumping when you as the player never pressed the button and disabled the auto-jump function? If the game has to punish you for jumping why do it when your character did a glitch move? 

I was on a hardcore world building on the water with half-slab bridge made of wood and full blocks on the sides of that bridge. I was on my way back to the house when I stepped into the water not completely submerged and automatically went from the halfslab to the full slab and died because the mod registered the player jumping. The player mechanics in water is a bit weird. 

Is there a way to make sure this mod registers you hitting the button to jump and not when the character itself does it? Otherwise I feel like the game won't last too long. I have disabled auto-jumping and changed my jump key so I don't hit it accidentally. If not, I might end up becoming hydrophobic and never build on the water.

I believe the game mechanics are at fault.

**Comment by JayJay1989** [comment]
i will look into this. thx for reporting this

**Comment by DatrixTHLK** [comment]
You're welcome and thanks for the response!

**Comment by JayJay1989** [comment]
Status on the research:
- its impossible to bind it to key input, on a multiplayer server it wouldn't register the keys.
- it should be possible to swim, you need the jump button anyways. 
- When you get knockback from a mob you die also

Possible solution:
- remove fall event.

Could you try the mod inside the zip?
[nojumpingallowed-1.0.1.jar.zip](https://github.com/JayJay1989/NoJumpingAllowed/files/3864124/nojumpingallowed-1.0.1.jar.zip)

**Comment by DatrixTHLK** [comment]
Sure. I'll let you know what I find out.

**Comment by DatrixTHLK** [comment]
Hi again,

Sorry to do this to you, but it turns out I missed something that I should have tried out before. You missed it too. It seems that when I try and climb up a ladder I automatically die for the same reason. I get on the ladder and then poof character is dead. Your mod must think it's a form of jumping when really it just going up, not jumping up. 

Correction I tried getting on a ladder, but I have to be right in front of it and not to the side of it or move in any direction while trying to climb up it else my character will die because of game mechanics and the mod. Why not test that out for yourself and see what I mean in a survival world.

Minecraft: 1.14.4
Forge: 28.1.90-28.1.93
nojumpingallowed: 1.0.1

**Comment by JayJay1989** [comment]
This issue should be fixed in the new release.

**Comment by DatrixTHLK** [comment]
Alright I'll test it out. Thanks for the fix and response! I appreciate it.

**Comment by DatrixTHLK** [comment]
I can now climb up the ladder and not die, but when I climb to the top of where the ladder ends that is where my character dies. 

Clip of example: 
https://youtu.be/iXOkGSvYA5k

Minecraft: 1.14.4
Forge: 28.1.96
nojumpingallowed: 1.0.2

**Comment by JayJay1989** [comment]
> Clip of example:
> https://youtu.be/iXOkGSvYA5k

video is private, cannot view it.
Here is my video: https://youtu.be/kXqYuUHkJY4

**Comment by DatrixTHLK** [comment]
I won't be using ladders then if that's the case and the clip should've been published already. I'll take a look

**Comment by DatrixTHLK** [comment]
Clip is published on my end, but is marked as whoever has the link can see it. I didn't die while on the ladder either. I died getting off the top part of the very last ladder. as the Clip showed: https://www.youtube.com/watch?v=iXOkGSvYA5k If this is still private, then I don't know what to tell you.

**Comment by JayJay1989** [comment]
I think its the same problem as the slabs and water.

**Comment by DatrixTHLK** [comment]
I see
